import {
  Branch,
  Barber,
  Chair,
  Service,
  Product,
  Booking,
  QueueEntry,
  AuditLog,
  Profile,
  SalonSettings,
} from '../types';

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-elhdad',
    name: 'الحداد - ELHDAD',
    address: 'سقيل - مركز اوسيم',
    phone: '01285694670',
    opening_time: '10:00',
    closing_time: '23:30',
    is_active: true,
    instapay_username: '01285694670',
    vodafone_cash_number: '01285694689',
    image_url: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&auto=format&fit=crop&q=80',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_BARBERS: Barber[] = [
  {
    id: 'barber-mohamed',
    branch_id: 'branch-elhdad',
    full_name: 'محمد الحداد',
    phone: '01285694670',
    specialty: 'كبير الحلاقين وقصات VIP الملكية',
    rating: 5.0,
    rating_count: 120,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'barber-karim',
    branch_id: 'branch-elhdad',
    full_name: 'كريم السيد',
    phone: '01123456789',
    specialty: 'قص شعر وتدريج عصري Fade',
    rating: 4.9,
    rating_count: 85,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'barber-omar',
    branch_id: 'branch-elhdad',
    full_name: 'عمر خالد',
    phone: '01098765432',
    specialty: 'عناية كاملة باللحية والبشرة',
    rating: 4.9,
    rating_count: 94,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_CHAIRS: Chair[] = [
  {
    id: 'chair-1',
    branch_id: 'branch-elhdad',
    barber_id: 'barber-mohamed',
    name: 'الكرسي الملكي VIP 1',
    mode: 'vip',
    status: 'available',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'chair-2',
    branch_id: 'branch-elhdad',
    barber_id: 'barber-karim',
    name: 'كرسي العناية 2',
    mode: 'normal',
    status: 'available',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'chair-3',
    branch_id: 'branch-elhdad',
    barber_id: 'barber-omar',
    name: 'كرسي العناية 3',
    mode: 'normal',
    status: 'available',
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_SERVICES: Service[] = [
  {
    id: 'srv-vip-executive',
    name: 'VIP Executive',
    description: 'الباقة التنفيذية الفاخرة لرجال الأعمال والنخبة (شاملة كل الخدمات والعناية الملكية والجناح الخاص)',
    price: 900,
    duration_minutes: 120,
    category: 'vip_package',
    is_vip_only: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-vip-royal',
    name: 'VIP Royal Cut',
    description: 'تجربة ملكية متكاملة لقص الشعر بأعلى مستوى من الدقة (جناح خاص ومكيف، كرسي مساج، شاشة سينما، دخول فوري بدون انتظار)',
    price: 650,
    duration_minutes: 60,
    category: 'vip_package',
    is_vip_only: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-vip-gentleman',
    name: 'VIP Gentleman',
    description: 'عناية شاملة ومميزة بالشعر واللحية في أجواء من الخصوصية التامة (جناح خاص، كرسي مساج، سينما، دخول فوري)',
    price: 650,
    duration_minutes: 90,
    category: 'vip_package',
    is_vip_only: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-haircut-beard',
    name: 'قص شعر + لحية',
    description: 'قص شعر متكامل وتحديد اللحية بالموس وحمام بخار تركي',
    price: 220,
    duration_minutes: 40,
    category: 'hair',
    is_vip_only: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-haircut-classic',
    name: 'قص شعر كلاسيكي',
    description: 'قص وتصفيف شعر احترافي مع غسيل وسشوار',
    price: 180,
    duration_minutes: 30,
    category: 'hair',
    is_vip_only: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-fade',
    name: 'تدريج Fade عصري',
    description: 'تدريج دقيق وعصري بأحدث الماكينات العالمية',
    price: 180,
    duration_minutes: 35,
    category: 'hair',
    is_vip_only: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-kids',
    name: 'قص شعر أطفال',
    description: 'قص شعر لطيف للأطفال مع ألعاب وشاشات ترفيهية',
    price: 150,
    duration_minutes: 25,
    category: 'kids',
    is_vip_only: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-espresso',
    branch_id: 'branch-elhdad',
    name: 'إسبريسو دبل فاخر',
    category: 'hot_drink',
    price: 35,
    is_active: true,
    description: 'قهوة إسبريسو إيطالية فاخرة 100% أرابيكا',
  },
  {
    id: 'prod-latte',
    branch_id: 'branch-elhdad',
    name: 'كافيه لاتيه بحليب الشوفان',
    category: 'hot_drink',
    price: 45,
    is_active: true,
    description: 'مزيج القهوة الغنية مع الحليب الرغوي',
  },
  {
    id: 'prod-fresh-juice',
    branch_id: 'branch-elhdad',
    name: 'عصير برتقال فريش طازج',
    category: 'cold_drink',
    price: 40,
    is_active: true,
    description: 'برتقال طبيعي معصور طازجاً بدون سكر مضاف',
  },
  {
    id: 'prod-energy-drink',
    branch_id: 'branch-elhdad',
    name: 'مشروب طاقة ريد بول',
    category: 'cold_drink',
    price: 50,
    is_active: true,
    description: 'مشروب منعش بارد',
  },
  {
    id: 'prod-beard-oil',
    branch_id: 'branch-elhdad',
    name: 'زيت اللحية الفاخر بالأرجان',
    category: 'care_product',
    price: 150,
    is_active: true,
    description: 'تغذية وتنعيم وترطيب عميق لشعر اللحية والشارب',
  },
  {
    id: 'prod-wax',
    branch_id: 'branch-elhdad',
    name: 'واكس تصفيف الشعر المطفي',
    category: 'care_product',
    price: 120,
    is_active: true,
    description: 'تثبيت قوي مع مظهر مطفي طبيعي يدوم طوال اليوم',
  },
];

export const INITIAL_SETTINGS: SalonSettings = {
  salon_name: (import.meta as any).env?.VITE_SALON_NAME || 'صالون الحلاقة والعناية VIP',
  tagline: 'الوجهة الأولى للرجل العصري الباحث عن الدقة والأناقة الفائقة',
  about_text: 'يقدم الصالون أرقى خدمات الحلاقة والعناية باللحية والبشرة، مع نظام حجز رقمي ذكي يضمن خصوصيتك وراحتك بدون أي انتظار.',
  primary_phone: (import.meta as any).env?.VITE_SALON_PHONE || '01285694670',
  secondary_phone: '01005437633',
  whatsapp_number: (import.meta as any).env?.VITE_SALON_WHATSAPP || '01005437633',
  working_hours_text: 'يومياً: 10:00 ص – 11:30 م (الحجز الإلكتروني متاح 24/7)',
  booking_fee_normal: 50,
  booking_fee_vip: 100,
  cancellation_grace_hours: 3,
  max_advance_days: 14,
  vodafone_cash_number: '01285694689',
  instapay_username: '01285694670',
  bank_account_info: '',
};

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'usr-customer-guest',
    full_name: 'عميل زائر',
    phone: '',
    email: '',
    role: 'customer',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr-manager-super',
    full_name: 'أحمد عبدالباسط (المدير العام)',
    phone: '01285694670',
    email: 'admin@salon.com',
    password: 'Admin@123456',
    role: 'manager',
    is_super_admin: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr-receptionist-main',
    full_name: 'موظف الاستقبال',
    phone: '01005437633',
    email: 'reception@salon.com',
    password: 'Admin@123456',
    role: 'receptionist',
    branch_id: 'branch-elhdad',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr-barber-mohamed',
    full_name: 'محمد الحداد',
    phone: '01285694670',
    email: 'barber@salon.com',
    password: 'Admin@123456',
    role: 'barber',
    barber_id: 'barber-mohamed',
    branch_id: 'branch-elhdad',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_BOOKINGS: Booking[] = [];

export const INITIAL_QUEUE: QueueEntry[] = [];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [];
